import { defineStore } from 'pinia';

export const useProfilesStore = defineStore("profiles", {
  state: () => ({
    profiles: [
      {
        id: "1",
        userId: "1",
        name: "Sergio",
        last: "Terrero",
        username: "Admin",
        email: "gio@gmail.com",
        gender: "male",
        age: 34,
        phone: "857-919-1517",
        dateCreated: "05/22/2023",
        dateUpdated: "05/25/2023",
        isAdmin: true,
        isActive: true,
      },

      {
        id: "2",
        userId: "2",
        name: "Jackie",
        last: "Terrero",
        username: "JTerrero",
        email: "jio@gmail.com",
        gender: "female",
        age: 30,
        password: "123",
        phone: "857-919-1518",
        dateCreated: "05/23/2023",
        dateUpdated: "05/25/2023",
        isAdmin: false,
        isActive: true,
      },
      {
        id: "3",
        userId: "3",
        name: "Ezra",
        last: "Terrero",
        username: "Exra",
        email: "Er@gmail.com",
        gender: "male",
        age: 29,
        password: "123",
        phone: "857-919-1519",
        dateCreated: "05/22/2023",
        dateUpdated: "05/25/2023",
        isAdmin: false,
        isActive: true,
      },

      {
        id: "4",
        userId: "4",
        name: "Camila",
        last: "Terrero",
        username: "JTerrero",
        email: "cam@gmail.com",
        gender: "female",
        age: 20,
        password: "123",
        phone: "857-919-1516",
        dateCreated: "05/23/2023",
        dateUpdated: "05/25/2023",
        isAdmin: false,
        isActive: true,
      },
    ],
  }),

  actions: {},
});
